apiVersion: 1

datasources:
  - name: InfluxDB
    uid: influxdb_solar
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: $INFLUX_ORG
      defaultBucket: solar_raw
      tlsSkipVerify: true
    secureJsonData:
      token: $INFLUX_TOKEN
